name: "Stochastic Analytics, LLC"
description: "The Homepage for Stochastic Analytics, LLC"

url: "http://clearnoise.org"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
